### ISSUE TITLE
EventDetector should not exist

### ISSUE THREAD

**Issue by stevenroose** [0xor1/eventable#17]
I think it is wrong to require classes listening to events to extend a certain class (or use a mixin).

This is of course a design decision, but I'm sure the class is not required.

**Comment by 0xor1** [comment]
could you explain how you would remove the mixin and what benefits it would bring? I believe I originally had a single class for making things do both emit and detect events, but the two do not have to be coupled together and since they are used as mixins it is very simple to add both to a class with no cost that I can think of.

**Comment by stevenroose** [comment]
In my opinion, an event "receiver" should not require special logic or variables in order to do so. All it needs is a method that can be called by the event emitter. This can be done either with an interface or by passing the method to the event emitter. The latter is what I'd prefer.

When creating a library with classes that emit events, you want to make it easy to use. You don't want users to add an extra dependency and change the class signature in which they use your library when the same can be achieved by just having the user call a method inside your library.

**Comment by stevenroose** [comment]
Don't take this too serious though, you probably thought it through more than I did.

I'm just comparing eventable to [event_emitter](https://github.com/JosephMoniz/dart-event-emitter/) and I think I will be going with the latter for simplicity. Even though I like eventable's class-based event typing better that event_emitter's strings.

**Comment by 0xor1** [comment]
fair points, I think I came at it with a specific ideology in mind, I like the eventDispatcher mrdoob uses in threejs and some of the methods used in backbonejs event system and so was influenced slightly by those but also had my own design patterns in mind. event _emitter looks nice and simple to use and certainly a good choice if it suites your needs. To be fair though eventable can be used in largely the same way.

In the example in event_emitter readme file the listener method is added to the emitter with:

`events.on("boom", handler);`

which can be the same as this in eventable:

```
//assuming events is an eventable EventEmitter
// Boom is a class type
// and handler is a function with signature (Event<Boom> event){}
events.addEventAction(Boom, handler);
```

you dont have to use EventDetector at all, it's more for convenience and following a particular design pattern and ideology that I like to use when working with an event system, but it is optional. So potentially with eventable you get more type checking since it listens for actual types rather than just strings, but maybe you get that with Event_Emitter too, I haven't looked into it beyond the ReadMe.

Cheers

**Comment by 0xor1** [comment]
for clarity, in eventable simply:

``` dart
import 'package:eventable/eventable.dart';

main() {

  var events  = new EventEmitter();
  var handler = (Event<Boom> event){ print("*** called handler"); }

  events.emitEvent(new Boom());
  print("should not have called handler.");

  events.addEventAction(Boom, handler);
  events.emitEvent(new Boom());
  print("should have called handler.");

  events.removeEventAction(Boom, handler);
  events.emitEvent(new Boom());
  print("should not have called handler.");

  /*
   // eventable EventEmitter does not have an analogous clearListeners method as 
  // this sort of thing is prefferred to be handled by the EvenDetector in eventable
  // as part of the main design pattern, is that event emitters shouldn't be aware or
  // care about who or what is listening to it. it is the detectors that choose what and when
  // to start and stop listening to  events so they have the more powerful removal methods such as
  //      ignoreSpecificEventBinding(EventEmitter emitter, Type type)
  //      ignoreAllEventsOfType(Type type)
  //      ignoreAllEventsFrom(EventEmitter emitter)
  //      ignoreAllEvents()
  events.addEventAction(Boom, handler);
  events.clearListeners();
  events.emit("boom", "some data");
  print("should not have called handler.");
 */
}
```
